#!/bin/bash
#
# Create a disk image where there exists a partition whose sizes matches the
# start sector.
# brought up under bug 1807171, which describes an error in the sed expression
# used to generate the replacement partition map

set -e

TEMP_D=""

rq() {
    local out="${TEMP_D}/out"
    "$@" > "$out" 2>&1 || { echo "FAILED:" "$@"; cat "$out"; return 1; }
}
fail() { echo "FAILED:" "$@" 1>&2; exit 1; }

setup_image() {
    sfdisk disk.img <<EOF
label: gpt
label-id: db24000c-6ef3-4a17-b71c-1064baa29514
device: disk.img
unit: sectors
first-lba: 2048
last-lba: 4194270

disk.img1 : start=        2048, size=     1024000, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, uuid=5bc16165-bfc0-4e13-94eb-b898dc0bca41
disk.img2 : start=     1026048, size=     1026048, type=4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709, uuid=a0e1636e-b759-4e7a-bd14-6f3d6c04745d
EOF
}

cleanup() {
    rm -rf "${TEMP_D}"
}

TEMP_D=$(mktemp -d ${TMPDIR:-/tmp}/${0##*/}.XXXXXX)
trap cleanup EXIT

# the sfdisk and sgdisk resizers result in slightly different output, because
# of course they do.

expected_sfdisk='label: gpt
label-id: DB24000C-6EF3-4A17-B71C-1064BAA29514
device: disk.img
unit: sectors
first-lba: 2048
last-lba: 4194270

disk.img1 : start=        2048, size=     1024000, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, uuid=5BC16165-BFC0-4E13-94EB-B898DC0BCA41
disk.img2 : start=     1026048, size=     3168223, type=4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709, uuid=A0E1636E-B759-4E7A-BD14-6F3D6C04745D'

expected_sgdisk='label: gpt
label-id: DB24000C-6EF3-4A17-B71C-1064BAA29514
device: disk.img
unit: sectors
first-lba: 2048
last-lba: 4192256

disk.img1 : start=        2048, size=     1024000, type=C12A7328-F81F-11D2-BA4B-00A0C93EC93B, uuid=5BC16165-BFC0-4E13-94EB-B898DC0BCA41
disk.img2 : start=     1026048, size=     3166208, type=4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709, uuid=A0E1636E-B759-4E7A-BD14-6F3D6C04745D'


CR='
'

test_resize () {
    local resizer=$1
    local expected=$2
	echo "====== Testing with resizer=$resizer ====="

    (
        cd ${TEMP_D}
        echo "$expected" > partitions.expected

        rq truncate "--size=2G" disk.img
        rq setup_image || fail "setup image $img"

        sfdisk --dump disk.img > partitions.before

        if ! GROWPART_RESIZER=$resizer \
                growpart -v -v disk.img 2 2>"stderr" > "stdout"; then
            cat "stderr" "stdout"
            fail "[resizer=$resizer] growpart failed"
        fi
        
        sfdisk --dump disk.img > partitions.after
        if ! diff -U0 partitions.expected partitions.after; then
            fail "[resizer=$resizer] partition table is incorrect"
        fi 
    )
}

set -e
test_resize sfdisk "$expected_sfdisk"
test_resize sgdisk "$expected_sgdisk"
