.TH uec\-publish\-image 1 "17 Feb 2010" cloud\-utils "cloud\-utils"
.SH NAME
uec\-publish\-image \- publish a cloud image

.SH SYNOPSIS
.BI "uec\-publish\-image [OPTIONS] ARCH IMAGE BUCKET

.SH OPTIONS
.TP
.B -l|--add-launch <user_id>
user_id can be "all", or "none"
.TP
.B --dry-run
only report what would be done
.TP
.B --allow-existing
if a image is already registered simply report as if work was done
.TP
.B -o|--output <file>
write registered id and manifest to file
.TP
.B    --rename <publish_path>
publish to bucket/<publish_path>, default: bucket/<basename(image)>
.TP
.B -t|--type   <type>
type is one of kernel/ramdisk/image.
if type is 'image', then:
  -k | --kernel       k : use previously registered kernel with id 'k'
                          specify 'none' for no kernel
  -K | --kernel-file  f : bundle, upload, use file 'f' as kernel
  -r | --ramdisk      r : use previously registered ramdisk with id 'r'
                          specify 'none' for no ramdisk
  -R | --ramdisk-file f : bundle, upload, use file 'f' as ramdisk
  -B | --block-device-mapping m : specify block device mapping in bundle

.TP
.B -v|--verbose
increase verbosity

.TP
.B    --name <name>
register image with given name. basename(publish_path)

.SH ARGUMENTS
.TP
.B ARCH
Target architecture, one of i386 or x86_64
.TP
.B IMAGE
Target image to upload and register
.TP
.B BUCKET
Target bucket to publish the image to

.SH ENVIRONMENT
Behavior of this program can be modified by environment variables as described below:

.TP
.B EC2PRE
Underlying tools will be invoked using this prefix.  The default is 'euca-', which results in using tools like 'euca-register' and 'euca-bundle-image'.  To use the ec2-api-tools or ec2-ami-tools, set EC2PRE='ec2-'

.SH DESCRIPTION
Publish an image to a cloud

.SH AUTHOR
This manpage was written by Dustin Kirkland <kirkland@canonical.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
