.TH uec\-query\-builds 1 "17 Feb 2010" cloud\-utils "cloud\-utils"
.SH NAME
uec\-query\-builds \- request information about available cloud images builds

.SH SYNOPSIS
.BI "uec\-query\-builds [is-update-available|latest]

.SH OPTIONS
.TP
.B is-update-available

.TP
.B latest

.SH DESCRIPTION
Request information about available cloud images, the latest version, and if updates are available.

.SH AUTHOR
This manpage was written by Dustin Kirkland <kirkland@canonical.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
