#!/bin/sh
set -e

share_d="/usr/share/cloud-utils"
gpg_d="${share_d}/dot-gnupg"

case "$1" in
    configure)
        if [ ! -e "${gpg_d}" ]; then
            mkdir -p "${gpg_d}"
        fi

        gpg --homedir "${gpg_d}" --import "${share_d}/cdimage.asc"
        gpg --homedir "${gpg_d}" --import-ownertrust "${share_d}/cdimage_trust.txt"

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        if [ -e "${gpg_d}"  ]; then
            rm -rf ${gpg_d}
        fi
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0

