#!/bin/sh

name="cloud-utils"
Usage() {
   cat <<EOF
Usage: ${0##*/} version
   make a tarball of 'version'
   must be in a bzr directory, and 'version' must be a tag

EOF
}

topdir=$PWD
tag=${1}

[ -n "$tag" ] || { Usage 1>&2 ; exit 1; }

tmpd=$(mktemp -d ); 
trap "rm -Rf '${tmpd}'" 0

out=${topdir}/$name-${tag}.tar.gz

cd ${tmpd} && 
   bzr branch -r "tag:${tag}" "${topdir}" ./${name}-${tag} &&
   rm -rf ${name}-${tag}/debian &&
   tar czf "${out}" ${name}-${tag}/ --exclude ${name}-${tag}/.bzr &&
   echo "wrote ${out}"
