name: cloud-utils ci

on: [push, pull_request]

jobs:
  tox:
    # Run on the oldest supported LTS
    runs-on: ubuntu-16.04
    steps:
      - name: Install dependencies
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get -qqy install tox
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Run tox
        run: tox
