name: cloud-utils ci

on: [push, pull_request]

jobs:
  tox:
    runs-on: ubuntu-18.04
    steps:
      - name: Update apt
        run: sudo apt-get update -q
      - name: Install dependencies
        run: sudo DEBIAN_FRONTEND=noninteractive apt-get -qqy install tox lvm2 fdisk gdisk qemu-utils busybox
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Run tox
        run: tox
      - name: Run tests
        # SKIP growpart-lvm test that does not work on github c-i
        run: sudo SKIP=growpart-lvm PATH=$PWD/bin:$PATH ./test/run-all
      - name: Run tests against BusyBox-based minimal environment
        run: |
          mkdir /tmp/busybox-bin
          busybox --install -s /tmp/busybox-bin
          ln -s $(command -v flock mkfs.ext4 qemu-img qemu-nbd resize2fs sfdisk sgdisk) /tmp/busybox-bin
          # Skip growpart: needs BusyBox >= 1.31, not available in Ubuntu yet.
          # Skip mic: needs BusyBox >= 1.31, not available in Ubuntu yet.
          sudo SKIP=mic,growpart,growpart-lvm PATH=$PWD/bin:/tmp/busybox-bin ./test/run-all
